# Generated by Django 5.0.7 on 2024-07-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_savedcarts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_title', models.CharField(max_length=200)),
                ('Restaurant_gif', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RenameField(
            model_name='regularpizza',
            old_name='category_description',
            new_name='Restaurant_description',
        ),
        migrations.RenameField(
            model_name='sicilianpizza',
            old_name='category_description',
            new_name='Restaurant_description',
        ),
    ]
